Presentation/Pages/ParkingSlots/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Application.ParkingSlots.Commands.CreateParkingSlot;
using Domain.Entities;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.ParkingSlots
{
	public class CreateModel : PageModel
    {
		private readonly IMediator _mediator;

        [Required]
        [MaxLength(10)]
        [BindProperty]
		public string Title {
            get; set;
        }

        public CreateModel(IMediator mediator) {
			_mediator = mediator;
		}

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync() {
            Result<int> result = await _mediator.Send(new CreateParkingSlotCommand(Title));
            if (result.IsError) {
				foreach (var error in result.Error.Errors) {
					ModelState.AddModelError("", error);
				}
				return Page();
			}
            return Redirect("/ParkingSlots/List");
               
	    }
    }
}

Presentation/Pages/ParkingSlots/List.cshtml.cs
using Application.ParkingSlots.Commands.DeleteParkingSlot;
using Application.ParkingSlots.Commands.OccupyParkingSlot;
using Application.ParkingSlots.Queries.GetFilteredParkingSlots;
using Application.ParkingSlots.Queries.GetParkingSlots;
using Domain.Entities;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.ParkingSlots
{
	public class ListModel : PageModel
    {
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		public List<ParkingSlot> ParkingSlots {
            get; set;
        }

        public ListModel(IMediator mediator, UserManager<User> userManager) {
			_mediator = mediator;
			_userManager = userManager;
		}

        public async Task OnGetAsync()
        {
			Result<List<ParkingSlot>> result = await _mediator.Send(new GetParkingSlotsQuery());
			ParkingSlots = result.Value;
        }

        public async Task<IActionResult> OnPostOccupyAsync(int id) {
			int userId = (await _userManager.GetUserAsync(User)).Id;
			Result<ParkingSlot> result = await _mediator.Send(new OccupyParkingSlotCommand(id, userId));
			return RedirectToAction("OnGetAsync");
	    }

		public async Task<IActionResult> OnPostDeleteAsync(int id) {
			await _mediator.Send(new DeleteParkingSlotCommand(id));
			return RedirectToAction("OnGetAsync");
		}

		public async Task<IActionResult> OnGetMyslotAsync() {
			int userId = (await _userManager.GetUserAsync(User)).Id;
			Result<List<ParkingSlot>> result = await _mediator.Send(new GetFilteredParkingSlotsQuery() { userId = userId });
			ParkingSlots = result.Value;
			return Page();
		}

		public async Task<IActionResult> OnGetFreeslotsAsync() {
			int userId = (await _userManager.GetUserAsync(User)).Id;
			Result<List<ParkingSlot>> result = await _mediator.Send(new GetFilteredParkingSlotsQuery() { Occupied = false });
			ParkingSlots = result.Value;
			return Page();
		}
	}
}

Presentation/Pages/Requests/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Application.Requests.Commands.CreateRequest;
using Domain.Entities;
using Domain.Enums;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.Requests
{
    [Authorize]
	public class CreateModel : PageModel
    {
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		[TempData]
        public string SubmitMessage {
            get; set;
        }

        [Required]
        [BindProperty]
        public string Title {
            get; set;
        }

		[Required]
		[BindProperty]
		public string Description {
			get; set;
		}

		[Required]
		[BindProperty]
		public RequestType Type {
			get; set;
		}

		public List<RequestType> RequestTypes {
            get; set;
        }

        public CreateModel(IMediator mediator, UserManager<User> userManager) {
			_mediator = mediator;
			_userManager = userManager;
			RequestTypes = Enum.GetValues(typeof(RequestType)).Cast<RequestType>().ToList();
		}

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync() {
            if (!ModelState.IsValid) 
				return Page();
            int id = (await _userManager.GetUserAsync(User)).Id;
            Result<int> result = await _mediator.Send(new CreateRequestCommand(Type, Title, Description, id));
            if (result.IsError) {
				result.Error.Errors.ForEach(e => ModelState.AddModelError("", e));
				return Page();
			}
			return Redirect("/Requests/List");
			
        }
    }
}

Presentation/Pages/Requests/List.cshtml.cs
using System.ComponentModel;
using Application.Requests.Commands.DeleteRequest;
using Application.Requests.Queries;
using Application.Requests.Queries.GetFilteredRequests;
using Domain.Entities;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.Requests
{
    [Authorize]
	public class ListModel : PageModel
    {
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		public List<Request> Requests {
            get; set;
        }

        [BindProperty(SupportsGet = true)]
        [DefaultValue(false)]
        public bool Finished {
            get; set;
        }

		public ListModel(IMediator mediator, UserManager<User> userManager) {
			_mediator = mediator;
			_userManager = userManager;
		}

        public async Task<IActionResult> OnGetAsync()
        {
            if (User.IsInRole("Admin")) {
                Result<List<Request>> result = await _mediator.Send(new GetFilteredRequestsQuery() { Completed = Finished});
                Requests = result.Value;
            } else {
                int userId = (await _userManager.GetUserAsync(User)).Id;
		        Result<List<Request>> result = await _mediator.Send(new GetFilteredRequestsQuery() { UserId = userId});
                Requests = result.Value;
	        }
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id) {
            await _mediator.Send(new DeleteRequestCommand(id));
            return RedirectToAction(Request.Path);
	    }
	}
}

Presentation/Pages/Users/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Application.Abstrations;
using Application.Users.Commands.CreateUser;
using Domain.Entities;
using Domain.Exceptions;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.Users
{
    [Authorize(Roles = "Admin")]
	[BindProperties]
	public class CreateModel : PageModel
    {
		private readonly IMediator _mediator;

		[Required]
		//[MaxLength(50)]
		public string FirstName {
			get; set;
		}

		[Required]
		[MaxLength(50)]
		public string LastName {
			get; set;
		}

		[Required]
		public int Age {
			get; set;
		}

		[Required]
		[MaxLength(300)]
		public string Position {
			get; set;
		}

		[Required]
		[MaxLength(300)]
		public string Email {
			get; set;
		}

		[Required]
		[DataType(DataType.Password)]
		[MinLength(8)]
		[MaxLength(30)]
		public string Password {
			get; set;
		}

		public CreateModel(IMediator mediator) {
			_mediator = mediator;
		}

		public async void OnGet()
        {
        }

        public async Task<IActionResult> OnPost() {
			if (!ModelState.IsValid)
				return Page();

			//try {
			Result<int> result = await _mediator.Send(new CreateUserCommand(FirstName, LastName, Age, Email, Position, Password));
			if (result.IsError) {
				result.Error.Errors.ForEach(e => ModelState.AddModelError("", e));	
				return Page();
			}
			return Redirect("/Users/List");
				
		}
    }
}

Presentation/Pages/Users/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Users.Commands.DeleteUser;
using Application.Users.Queries.GetUsers;
using Domain.Entities;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EmptyResult = Domain.Shared.EmptyResult;

namespace Presentation.Pages.Users
{
	public class ListModel : PageModel
    {
        public IMediator _mediator {
            get; set;
        }

        public List<User> Users {
            get; set;
        }

        public ListModel(IMediator mediator) {
            _mediator = mediator;
        }

        [Authorize]
        public async Task OnGet()
        {
            Result<List<User>> result = await _mediator.Send(new GetUsersQuery());
            Users = result.Value;
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id) {
            EmptyResult result =  await _mediator.Send(new DeleteUserCommand(id));
            if (result.IsError) {
                result.Error.Errors.ForEach(e => ModelState.AddModelError("", e));
	        }
            return Redirect("/Users/List");
	    }
    }
}

Presentation/Pages/ParkingSlots/Create.cshtml
@page
@model Presentation.Pages.ParkingSlots.CreateModel
@{
    <div class="flex flex-col w-full items-center pt-2">
        <partial name="Includes/_FormValidation"></partial>
        <form method="post" class="flex flex-col w-1/2">
            <div class="flex flex-col w-100 p-2">
                <label for="Title" class="text-sm">Title:</label>
                <input class="h-10 border border-gray-400 rounded-sm mt-1 p-2" name="Title" placeholder="Title" />
            </div>
            <button class="rounded-sm bg-green-400 hover:bg-green-900 text-green-900 hover:text-white drop-shadow-sm h-10 transition">Create</button>
        </form>
    </div>
}

Presentation/Pages/ParkingSlots/List.cshtml
@page
@model Presentation.Pages.ParkingSlots.ListModel
@{
    <div class="flex flex-col items-center w-full">
        <div class="w-full flex align-left">
            @if (User.IsInRole("Admin"))
            {
                <a href="/ParkingSlots/Create">
                    <button class="p-4 m-4 bg-green-300 hover:bg-green-500 transition text-white rounded-sm shadow-drop-sm">Create slot</button>
                </a>

            }
            <form method="get">
                <button type="submit" class="p-4 m-4 bg-green-300 hover:bg-green-500 transition text-white rounded-sm shadow-drop-sm">Show all slots</button>
            </form>
            <form method="get">
                <input type="hidden" name="handler" value="myslot" />
                <button type="submit" class="p-4 m-4 bg-green-300 hover:bg-green-500 transition text-white rounded-sm shadow-drop-sm">Show my slot</button>
            </form>
            <form method="get">
                <input type="hidden" name="handler" value="freeslots" />
                <button type="submit" class="p-4 m-4 bg-green-300 hover:bg-green-500 transition text-white rounded-sm shadow-drop-sm">Show free slots</button>
            </form>

        </div>
        <table class="text-left rounded-lg w-full shadow-drop-sm text-white p-2">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">Id</th>
                    <th scope="col" class="px-6 py-3">Name</th>
                    <th scope="col" class="px-6 py-3">Occupied by</th>
                    <th scope="col" class="px-6 py-3"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var slot in @Model.ParkingSlots)
                    {
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                        <td class="px-6 py-4">@slot.Id</td>
                        <td class="px-6 py-4">@slot.Name</td>
                        @if(slot.OccupiedBy is not null) { 
                            <td class="px-6 py-4">@slot.OccupiedBy.FullName</td>
			            } else { 
                            <td class="px-6 py-4">This slot is free!</td>
			            }
                        
                    <td class="px-6 py-4">
                        @if (slot.OccupiedBy is null)
                        {
                            <form method="post" asp-page-handler="occupy" asp-route-id="@slot.Id">
                                <button type="submit" class="rounded-sm shadow-drop-sm bg-green-500 text-white p-1 mb-2">Occupy</button>
                            </form>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <form method="post" asp-page-handler="delete" asp-route-id="@slot.Id">
                                <button type="submit" class="rounded-sm shadow-drop-sm bg-red-500 text-white p-1 mb-2">Delete</button>
                            </form>
                        }
                        </td>
                        


                    </tr>
                    }
            </tbody>
        </table>
    </div>
    }