Presentation/Pages/ParkingSlots/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Application.ParkingSlots.Commands.CreateParkingSlot;
using Domain.Entities;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.ParkingSlots
{
	public class CreateModel : PageModel
    {
		private readonly IMediator _mediator;

        [Required]
        [MaxLength(10)]
        [BindProperty]
		public string Title {
            get; set;
        }

        public CreateModel(IMediator mediator) {
			_mediator = mediator;
		}

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync() {
            Result<int> result = await _mediator.Send(new CreateParkingSlotCommand(Title));
            if (result.IsError) {
				foreach (var error in result.Error.Errors) {
					ModelState.AddModelError("", error);
				}
				return Page();
			}
            return Redirect("/ParkingSlots/List");
               
	    }
    }
}

Presentation/Pages/ParkingSlots/List.cshtml.cs
using Application.ParkingSlots.Commands.DeleteParkingSlot;
using Application.ParkingSlots.Commands.OccupyParkingSlot;
using Application.ParkingSlots.Queries.GetFilteredParkingSlots;
using Application.ParkingSlots.Queries.GetParkingSlots;
using Domain.Entities;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.ParkingSlots
{
	public class ListModel : PageModel
    {
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		public List<ParkingSlot> ParkingSlots {
            get; set;
        }

        public ListModel(IMediator mediator, UserManager<User> userManager) {
			_mediator = mediator;
			_userManager = userManager;
		}

        public async Task OnGetAsync()
        {
			Result<List<ParkingSlot>> result = await _mediator.Send(new GetParkingSlotsQuery());
			ParkingSlots = result.Value;
        }

        public async Task<IActionResult> OnPostOccupyAsync(int id) {
			int userId = (await _userManager.GetUserAsync(User)).Id;
			Result<ParkingSlot> result = await _mediator.Send(new OccupyParkingSlotCommand(id, userId));
			return RedirectToAction("OnGetAsync");
	    }

		public async Task<IActionResult> OnPostDeleteAsync(int id) {
			await _mediator.Send(new DeleteParkingSlotCommand(id));
			return RedirectToAction("OnGetAsync");
		}

		public async Task<IActionResult> OnGetMyslotAsync() {
			int userId = (await _userManager.GetUserAsync(User)).Id;
			Result<List<ParkingSlot>> result = await _mediator.Send(new GetFilteredParkingSlotsQuery() { userId = userId });
			ParkingSlots = result.Value;
			return Page();
		}

		public async Task<IActionResult> OnGetFreeslotsAsync() {
			int userId = (await _userManager.GetUserAsync(User)).Id;
			Result<List<ParkingSlot>> result = await _mediator.Send(new GetFilteredParkingSlotsQuery() { Occupied = false });
			ParkingSlots = result.Value;
			return Page();
		}
	}
}

Presentation/Pages/Requests/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Application.Requests.Commands.CreateRequest;
using Domain.Entities;
using Domain.Enums;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.Requests
{
    [Authorize]
	public class CreateModel : PageModel
    {
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		[TempData]
        public string SubmitMessage {
            get; set;
        }

        [Required]
        [BindProperty]
        public string Title {
            get; set;
        }

		[Required]
		[BindProperty]
		public string Description {
			get; set;
		}

		[Required]
		[BindProperty]
		public RequestType Type {
			get; set;
		}

		public List<RequestType> RequestTypes {
            get; set;
        }

        public CreateModel(IMediator mediator, UserManager<User> userManager) {
			_mediator = mediator;
			_userManager = userManager;
			RequestTypes = Enum.GetValues(typeof(RequestType)).Cast<RequestType>().ToList();
		}

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync() {
            if (!ModelState.IsValid) 
				return Page();
            int id = (await _userManager.GetUserAsync(User)).Id;
            Result<int> result = await _mediator.Send(new CreateRequestCommand(Type, Title, Description, id));
            if (result.IsError) {
				result.Error.Errors.ForEach(e => ModelState.AddModelError("", e));
				return Page();
			}
			return Redirect("/Requests/List");
			
        }
    }
}

Presentation/Pages/Requests/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Application.Requests.Commands.DeleteRequest;
using Application.Requests.Commands.UpdateRequest;
using Application.Requests.Queries.GetRequestById;
using Domain.Entities;
using Domain.Enums;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.Requests
{
	[Authorize]
	public class IndexModel : PageModel
    {
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		public Request request {
			get; set;
		}
		//[BindProperty]
		//[Required]
		//[MaxLength(200)]
		//public string Title {
		//	get; set;
		//}

		//[BindProperty]
		//[Required]
		//[MaxLength(500)]
		//public string Description {
		//	get; set;
		//}

		//public bool Completed {
		//	get; set;
		//}
		public class RequestTypeOption
		{
			public RequestType type {
				get; set;
			}

			public bool selected {
				get; set;
			}
		}

		public List<RequestTypeOption> RequestTypes {
			get; set;
		} = new();

		[BindProperty(SupportsGet = true)]
		public int Id {
			get; set;
		}

		public bool Disabled {
			get; set;
		}

		public IndexModel(IMediator mediator, UserManager<User> userManager) {
			_mediator = mediator;
			_userManager = userManager;
		}

        public async Task<IActionResult> OnGetAsync()
        {
			Result<Request> result = await _mediator.Send(new GetRequestByIdQuery(Id));

			if (!User.IsInRole("Admin") && result.Value.UserId != (await _userManager.GetUserAsync(User)).Id) {
				return Redirect("/Requests/List");
			}

			request = result.Value;

			foreach (var type in Enum.GetValues(typeof(RequestType)).Cast<RequestType>().ToList()) {
				RequestTypeOption requestType = new() {
					type = type,
					selected = type == request.RequestType ? true : false
				};
				RequestTypes.Add(requestType);
			}
			
			Disabled = User.IsInRole("Worker") ? false : true;
			return Page();
        }


		public async Task<IActionResult> OnPostDelete() {
            Domain.Shared.EmptyResult result = await _mediator.Send(new DeleteRequestCommand(Id));
			if (result.IsError) {
				foreach (var error in result.Error.Errors) {
					ModelState.AddModelError("", error);
				}
				return Page();
			}
			return Redirect("/Requests/List");

		}

		public async Task<IActionResult> OnPostUpdateAsync(Request request) {
			request.UserId = (await _userManager.GetUserAsync(User)).Id;
			Result<Request> result = await _mediator.Send(new UpdateRequestCommand(request));
			if (result.IsError) {
				foreach (var error in result.Error.Errors) {
					ModelState.AddModelError("", error);
				}
			}

			return RedirectToAction("OnGetAsync", new { Id = result.Value.Id });
		}

		public IActionResult OnGetEdit() {
			Disabled = false;
			return Page();
		}

		protected void checkUser() {
		
		}
	}
}

Presentation/Pages/Requests/List.cshtml.cs
using System.ComponentModel;
using Application.Requests.Commands.DeleteRequest;
using Application.Requests.Queries;
using Application.Requests.Queries.GetFilteredRequests;
using Domain.Entities;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.Requests
{
    [Authorize]
	public class ListModel : PageModel
    {
		private readonly IMediator _mediator;
		private readonly UserManager<User> _userManager;

		public List<Request> Requests {
            get; set;
        }

        [BindProperty(SupportsGet = true)]
        [DefaultValue(false)]
        public bool Finished {
            get; set;
        }

		public ListModel(IMediator mediator, UserManager<User> userManager) {
			_mediator = mediator;
			_userManager = userManager;
		}

        public async Task<IActionResult> OnGetAsync()
        {
            if (User.IsInRole("Admin")) {
                Result<List<Request>> result = await _mediator.Send(new GetFilteredRequestsQuery() { Completed = Finished});
                Requests = result.Value;
            } else {
                int userId = (await _userManager.GetUserAsync(User)).Id;
		        Result<List<Request>> result = await _mediator.Send(new GetFilteredRequestsQuery() { UserId = userId});
                Requests = result.Value;
	        }
            return Page();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id) {
            await _mediator.Send(new DeleteRequestCommand(id));
            return RedirectToAction(Request.Path);
	    }
	}
}

Presentation/Pages/Users/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Application.Abstrations;
using Application.Users.Commands.CreateUser;
using Domain.Entities;
using Domain.Exceptions;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Presentation.Pages.Users
{
    [Authorize(Roles = "Admin")]
	[BindProperties]
	public class CreateModel : PageModel
    {
		private readonly IMediator _mediator;

		[Required]
		//[MaxLength(50)]
		public string FirstName {
			get; set;
		}

		[Required]
		[MaxLength(50)]
		public string LastName {
			get; set;
		}

		[Required]
		public int Age {
			get; set;
		}

		[Required]
		[MaxLength(300)]
		public string Position {
			get; set;
		}

		[Required]
		[MaxLength(300)]
		public string Email {
			get; set;
		}

		[Required]
		[DataType(DataType.Password)]
		[MinLength(8)]
		[MaxLength(30)]
		public string Password {
			get; set;
		}

		public CreateModel(IMediator mediator) {
			_mediator = mediator;
		}

		public async void OnGet()
        {
        }

        public async Task<IActionResult> OnPost() {
			if (!ModelState.IsValid)
				return Page();

			//try {
			Result<int> result = await _mediator.Send(new CreateUserCommand(FirstName, LastName, Age, Email, Position, Password));
			if (result.IsError) {
				result.Error.Errors.ForEach(e => ModelState.AddModelError("", e));	
				return Page();
			}
			return Redirect("/Users/List");
				
		}
    }
}

Presentation/Pages/Users/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Users.Commands.DeleteUser;
using Application.Users.Queries.GetUsers;
using Domain.Entities;
using Domain.Shared;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EmptyResult = Domain.Shared.EmptyResult;

namespace Presentation.Pages.Users
{
	public class ListModel : PageModel
    {
        public IMediator _mediator {
            get; set;
        }

        public List<User> Users {
            get; set;
        }

        public ListModel(IMediator mediator) {
            _mediator = mediator;
        }

        [Authorize]
        public async Task OnGet()
        {
            Result<List<User>> result = await _mediator.Send(new GetUsersQuery());
            Users = result.Value;
        }

        public async Task<IActionResult> OnPostDeleteAsync(int id) {
            EmptyResult result =  await _mediator.Send(new DeleteUserCommand(id));
            if (result.IsError) {
                result.Error.Errors.ForEach(e => ModelState.AddModelError("", e));
	        }
            return Redirect("/Users/List");
	    }
    }
}

Presentation/Pages/Requests/Create.cshtml
@page
@model Presentation.Pages.Requests.CreateModel
@{
    <div class="flex flex-col w-full items-center pt-2">
        <partial name="Includes/_FormValidation"></partial>
        <form method="post" class="flex flex-col w-1/2">
            <div class="flex flex-col w-100 p-2">
                <label for="Title" class="text-sm">Title:</label>
                <input class="h-10 border border-gray-400 rounded-sm mt-1 p-2" name="Title" placeholder="Title" />
            </div>

            <div class="flex flex-col w-100 p-2">
                <label for="Description" class="text-sm">Description:</label>
                <textarea class="h-30 border border-gay-400 rounded-md mt-1 p-2 w-full" name="Description" placeholder="Description"></textarea>
	        </div>
            <div class="flex flex-col w-100 p-2">
	            <label class="text-sm" for="RequestType">Type:</label>
                <select class="h-10 border border-gray-400 rounded-sm mt-1 p-2" name="Type">
		            @foreach(var type in Model.RequestTypes) { 
			            <option value="@type">@type</option>
			        }
		        </select>
	        </div>
            <button class="rounded-sm bg-green-400 hover:bg-green-900 text-green-900 hover:text-white drop-shadow-sm h-10 transition">Create</button>
        </form>
    </div>
}

Presentation/Pages/Requests/Index.cshtml
@page
@model Presentation.Pages.Requests.IndexModel
@{
    <div class="flex w-full flex-col items-center">
        <form method="post" asp-page-handler="update" class="flex flex-col w-1/2 p-2 rounded-sm shadow-drop sm bg-gray-300 my-4">
            <input type="hidden" name="request.Id" value="@Model.Id">
            @if (User.IsInRole("Admin"))
            {
                <div class="flex flex-col w-100 p-2">
                    <span class="text-sm underline">Created by @Model.request.CreatedBy.FirstName @Model.request.CreatedBy.LastName</span>
                </div>
            }
            <div class="flex flex-col w-100 p-2">
                <label for="Title" class="text-sm">Title:</label>
                <input disabled="@Model.Disabled" class="h-10 border border-gray-400 rounded-sm mt-1 p-2" name="request.Title" placeholder="Title" value="@Model.request.Title" id="Title" />
            </div>
            <div class="flex flex-col w-100 p-2">
                <label for="Description" class="text-sm">Description:</label>
                <textarea disabled="@Model.Disabled" class="border border-gray-400 rounded-sm mt-1 p-2" name="request.Description" id="Description">@Model.request.Description</textarea>
            </div>
            <div class="flex flex-col w-100 p-2">
                <label for="Title" class="text-sm">Type:</label>
                <select class="border border-gray-400 rounded-sm mt-1 p-2" disabled="@Model.Disabled" name="request.RequestType">
                    @foreach (var type in Model.RequestTypes)
                    {
                        <option value="@type.type" selected="@type.selected">@type.type</option>
                    }
                </select>
            </div>
            @if (User.IsInRole("Admin"))
            {
                @if (!Model.request.Completed)
                {
                    <input type="hidden" name="request.Completed" value="true" />
                    <button class="rounded-sm bg-green-400 hover:bg-green-900 text-green-900 hover:text-white drop-shadow-sm h-10 transition">Mark completed</button>
                }
                else
                {
                    <input type="hidden" name="request.Completed" value="false" />
                    <button class="rounded-sm bg-red-400 hover:bg-red-900 text-green-900 hover:text-white drop-shadow-sm h-10 transition">Mark uncompleted</button>
                }
            }


            @if (User.IsInRole("Worker") && !Model.request.Completed)
            {
                <button class="rounded-sm bg-green-400 hover:bg-green-900 text-green-900 hover:text-white drop-shadow-sm h-10 transition">Save</button>

            }
        </form>
        <form method="post" asp-page-handler="delete" asp-route-id="@Model.Id">
            @if (!Model.request.Completed && Model.Disabled)
            {
                <button class="rounded-sm bg-red-400 hover:bg-red-900 text-white-900 hover:text-white drop-shadow-sm h-10 transition">Delete</button>
            }
        </form>

    </div>
}

Presentation/Pages/Requests/List.cshtml
@page
@model Presentation.Pages.Requests.ListModel
@{
    <div class="flex flex-col items-center w-full">
        <div class="w-full flex align-left">
            @if (User.IsInRole("Admin"))
            {
                <a href="/Requests/Create">
                    <button class="p-4 m-4 bg-green-300 hover:bg-green-500 transition text-white rounded-sm shadow-drop-sm">Create request</button>
                </a>

            }
            @if (User.IsInRole("Admin"))
            {
                <a href="@Url.RouteUrl(new {Finished = !Model.Finished})">
                    @if(!Model.Finished) { 
                        <button class="p-4 m-4 bg-green-300 hover:bg-green-500 transition text-white rounded-sm shadow-drop-sm">Show finished requests</button>
			        } else { 
                        <button class="p-4 m-4 bg-green-300 hover:bg-green-500 transition text-white rounded-sm shadow-drop-sm">Show active requests</button>
			        }

                </a>

            }
        </div>
        <table class="text-left rounded-lg w-full shadow-drop-sm text-white p-2">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">Id</th>
                    <th scope="col" class="px-6 py-3">Title</th>
                    <th scope="col" class="px-6 py-3">Description</th>
                    <th scope="col" class="px-6 py-3">Type</th>
                    <th scope="col" class="px-6 py-3">From</th>
                    @if (User.IsInRole("Admin"))
                    {
                        <th scope="col" class="px-6 py-3"></th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var request in @Model.Requests)
                    {
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                        <td class="px-6 py-4">@request.Id</td>
                        <td class="px-6 py-4" ">@request.Title</td>
                        <td class="px-6 py-4" ">@request.Description</td>
                        <td class="px-6 py-4">@request.RequestType</td>
                        <td class="px-6 py-4">@request.UserId</td>
                        @if (User.IsInRole("Admin"))
                        {
                            <td class="px-6 py-4">
                                <form method="post" asp-page-handler="delete" asp-route-id="@request.Id">
                                    <button type="submit" class="rounded-sm shadow-drop-sm bg-red-500 text-white p-1 mb-2">Delete</button>
                                </form>
                                <a asp-route-id="@request.Id" asp-page="/Requests/Index">
                                    <button type="button" class="rounded-sm shadow-drop-sm bg-yellow-500 text-gray-800 p-1">Details</button>
				                </a>
                            </td>
                            }

                    </tr>
                  }
                </tbody>
        </table>
    </div>
}